### ISSUE TITLE
Blog post to show off pint-xarray integration?

### ISSUE THREAD

**Issue by TomNicholas** [xarray-contrib/pint-xarray#114]
@rabernat suggested to me that as a cool new feature the pint-xarray integration deserves it's own blog post to advertise it!

We could put it on the pangeo blog. It doesn't need to be a major undertaking, it would just be good to have an overview to refer to when mentioning this feature, and I think we're at the point where we want people to be trying this code out.

I'm happy to write this, but was wondering if
1) Anyone else was interested in helping (@keewis @jthielen ?) (you would be credited with all this excellent work regardless of course)
2) Are there any features/bugfixes we should wait for before writing it? True unit-aware indexes would be cool but that also will take a while...
3) Any particular ideas for cool unit problems to use as an example?

**Comment by jthielen** [comment]
Sounds like a great idea! If this is something in the near-term (e.g. 1-3 weeks), I will unfortunately be unable to help as I am currently finalizing my thesis. But, if it is something more on the next couple months timeline, I'd be glad to help, as I really want to get back into more open source contributions after my defense.

While it is not strictly a feature/bugfix to wait for on pint-xarray's end, I think it would be great to make sure that pint-xarray and cf-xarray can work well together (especially with cf-xarray's UDUNITS-emulating pint registry that follows from MetPy's approach). Being able to showcase seamless unit-aware analysis of CF-compliant earth science datasets would be a great selling point. I think the most work that remains is seeing if one library's accessors could utilize the other's when it is available (so that things like `ds.temperature.cf.isel(Z=850 * units.hPa)` work). But, if this is too much of a lift in the timeline for the blog post, then it can probably just be referenced as a roadmap item.

**Comment by dcherian** [comment]
> pint-xarray and cf-xarray can work well together (especially with cf-xarray's UDUNITS-emulating pint registry that follows from MetPy's approach).

I got started on this here: https://github.com/NCAR/pop-tools/pull/88; but then paused for the unit registry work in cf-xarray. We could adapt it to a few cloud datasets instead of NCAR-local datasets

**Comment by rabernat** [comment]
I support this 💯 . @jhamman is an editor on the Pangeo medium blog and can make sure you have permissions to submit a story.

**Comment by keewis** [comment]
I agree, that would be great, and since I currently have lots of time I would be able to help. Unfortunately, I don't have any ideas for examples (if I had we would have more tutorials) so thanks for the suggestion, @dcherian.

I don't think we have to wait for any bug fixes or new features right now: there were no bug reports involving `pint-xarray` since the last release (could be because the package is not that widely used) but there are a few things we need to figure out, e.g. the best way to interact with registries provided by a separate package or getting `xarray` to pass the duck arrays to `matplotlib` so the `matplotlib.units` feature works. I don't think we have to wait on those, though: for now, we can tell people to make sure to import packages like `cf-xarray` before `pint-xarray` and recommend `dequantify`ing before plotting.

**Comment by keewis** [comment]
@TomNicholas, can we compile a list of features we want to demonstrate in the blog post? I think that would make it much easier to get started.

**Comment by TomNicholas** [comment]
Thanks for the reminder @keewis - here's a list I had already made:

### Things we want to show off:
- Actual benefits of using Pint vs bare numpy (e.g. raising an error on some invalid operation that you might not have noticed otherwise)
- Automatic decoding of units in attributes (being able to just read a netCDF file and `quantify` automatically is super helpful)
- `cf_xarray` integration?
- Dask integration (this is a must-have for man users so we want to at least mention it, but requires https://github.com/pydata/xarray/pull/5571)
- Automatically plotting the correct units (small but a nice quality-of-life feature to point out)
- Point to the wrapped functions like `sel` else that will likely trip people up.

### Ideas for format of blog post

Some random ideas - these might also be useful for examples in the pint-xarray docs.

1) Velocity over time graphs
- Show division (m/s)
- Show wrapped functions (integrate to get displacement?)
- Not geoscience specific
- Everyone will understand it
- Unexciting

2) [Story of NASA orbiter lost](https://www.simscale.com/blog/2017/12/nasa-mars-climate-orbiter-metric/) due to metric-imperial mix up

3) CMIP6 use case
- Real research use case
- Geoscience specific

**Comment by TomNicholas** [comment]
I've drafted a blog post in #142. It's like 90% written, but I do think we should fix #141 before releasing it, and I could do with help to make a cool example that uses `cf_xarray.units`. We will also need another release of xarray first, because we need to inlcude https://github.com/pydata/xarray/pull/5571 in order for dask to work with pint.

This can either go on the pangeo Medium blog, or we can make a new xarray blog for xarray-related announcements. Ryan suggested that if we go with the latter we could use [dev.to](https://dev.to/) instead of Medium, as it is apparently better for technical content. For now the blog posts just exists in markdown form in #142 - feel free to make comments or suggest changes.

**Comment by keewis** [comment]
with the release of `pint=0.19` the last big blocker of the blog post is finally going to disappear (as far as I can tell the only task left is to actually make the release), so I'm wondering whether we should try to schedule a dedicated meeting to finish that, and to maybe also discuss the general direction of the package.

What do you think, @TomNicholas, @jthielen?
