### ISSUE TITLE
Unexpected unit conversion from Celsius to Kelvin when multiplying two DataArrays

### ISSUE THREAD

**Issue by paigem** [xarray-contrib/pint-xarray#146]
I have just started to use `pint-xarray` and have found that there is an unexpected conversion from Celsius to Kelvin when I multiply two `xarray.DataArrays` together. Below I have included a reproducible example of this:

```python
import numpy as np
import xarray as xr
import cf_xarray.units
import pint_xarray

time = np.arange(10)

data = xr.DataArray(np.arange(-1,1,0.2), coords=[time], dims=['time'], attrs={'units':'degC'})
data_quantified = data.pint.quantify()
data_quantified
```
Output: 
![image](https://user-images.githubusercontent.com/26591824/142569681-64dd8d6f-bc96-4e9f-81a5-186fe2762cd2.png)

Now if I try to square the quantity, I would expect to get units of degC^2, but instead it looks like the units have been converted to Kelvin and then squared:

```python
data_quantified**2
```
Output:
![image](https://user-images.githubusercontent.com/26591824/142569704-6f2f52de-0afc-427c-9431-a557073fb3d8.png)

This same behavior occurs when multiplying `data_quantified` with any `xarray.DataArray` that has different units as well. As far as I can tell, I haven't found the same behavior with any other unit except `degC`.

I am using `pint-xarray` version 0.2.1 on Pangeo Cloud, installed via pip.

As I am very new to this package, I'm not sure where to look for the source of this bug, so any help or input on this would be appreciated!

**Comment by jthielen** [comment]
While this may be surprising at first, this is actually the expected behavior! Since temperature units like degrees Celsius have an offset (i.e. 0 is not actually 0 in an absolute sense), they are *non-multiplicative*, or in other words, trying to multiply quantities in those units is not well-defined. To get around this, Pint (at least how it is configured by default in pint-xarray) automatically converts such non-multiplicative units to the corresponding absolute version--hence Kelvin here.

If you're interested in reading more about how these kinds of units work in Pint, I recommend this page of the documentation: https://pint.readthedocs.io/en/stable/nonmult.html

**Comment by paigem** [comment]
Thanks @jthielen - I see now why this is the expected behavior, and apologies that I didn't see that page in the docs before opening this issue. I'll go ahead and close this issue then!
